[package]
name = "magic_gt"
version = "0.1.0"
authors = ["HUANG Cheng <cheng@duck.com>"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
undrift_gps = "0.3.1"
xml-rs = "0.8.19"
regex = "1.8.1"
